### ISSUE TITLE
Could not pass event PlayerInteractEvent to Skywars v5.3.3

### ISSUE THREAD

**Issue by Aramus101** [lukasvdgaag/SkyWarsReloaded#11]
An error occurs while running the plugin with Spigot 1.16.4 - https://mcpaste.io/eba4e8cd7e28516c

This caused by right-clicking the "Select Kit" eye-of-ender item when in a Skywars arena.

config.yml: https://mcpaste.io/64bb10d77d6d67b2

**Comment by TechnicallyCoded** [comment]
Please update WorldEdit and delete the existing configuration file for WorldEdit edit to make sure it is up to date.
