### ISSUE TITLE
Set perms on custom cage

### ISSUE THREAD

**Issue by broken1arrow** [lukasvdgaag/SkyWarsReloaded#12]
I suggest perms on custom made cage, So you can do so player can buy this other ways easy (and cage will not give any gameplay advantages).

Kit you can set perms on can you set up so players can get advantage over other players, but not in same way with cage (if you not make it consciously design them to give advantages over the vanilla ones). In that case, players will see quite clearly and complain about this.

**Comment by TechnicallyCoded** [comment]
As per the description on the spigot page:
```
sw.glasscolor.[name]: 
Allows a player you use a glass color without having the required level. [name] represents the “Key” for the glass color in the glasscolors.yml.```
You can already allow players to purchase the permission to cages
