### ISSUE TITLE
Console Error 5.5.0

### ISSUE THREAD

**Issue by LucidAPs** [lukasvdgaag/SkyWarsReloaded#17]
Console error with version 5.5.0 , it happens when the server starts.
https://nekobin.com/fidujekaqa

**Comment by TechnicallyCoded** [comment]
You have an invalid material in the configuration. 
Here is a list of the item types you can put in the config in 1.16.5
[https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html]
And here is the list for 1.8.8
[https://helpch.at/docs/1.8.8/org/bukkit/Material.html]

**Comment by TechnicallyCoded** [comment]
No reply.
