### ISSUE TITLE
Registration process occurs after the saving process

### ISSUE THREAD

**Issue by Budderman18** [lukasvdgaag/SkyWarsReloaded#23]
In order to save a map, you must register it first. However, when you go to register a map, it has to save it first. However, when the game goes to save a map, my guess is it checks to see if a map was registered. If it isn't, it doesn't save. Then after that, the map gets registered. Because of this, saving maps is currently impossible (since maps unregister themselves when being edited, and you can't save a map that's not in edit mode). 

The console does not output any errors, so I don't really have anything else to show.

**Comment by Budderman18** [comment]
If you try and save a map that isnt registered, it'll say "This map needs to be registered first!", and deletes the world. If you then go to register, it will succeed but will kick you out and wont save anything. If you try to edit a map the is registered, it will unregister itself, putting you in an infinite loop of trying to save but the plugin essentially not allowing it.

**Comment by TechnicallyCoded** [comment]
![image](https://user-images.githubusercontent.com/29813490/128869867-f78133c0-d98c-46a9-b66b-1dc21a08eb4f.png)
That message does not exist in the plugin.

**Comment by Budderman18** [comment]
"You have to register the arena to save your changes!" is exactly what it says

**Comment by Budderman18** [comment]
Update: The latest update kindve fixed this. Sometimes the maps wont save, but sometimes they do. Again, no errors show up.

**Comment by TechnicallyCoded** [comment]
I just checked the code, and that does no prevent it from being saved. It is mostly not said correctly. I was supposed to say that you need to register in order for the map to be joinable.
