### ISSUE TITLE
Major issue for 102 users in Aternos!

### ISSUE THREAD

**Issue by Aadi-mone** [lukasvdgaag/SkyWarsReloaded#24]
### Minecraft's Version

Paper 1.16.5

### Plugin's Version

1.7.0 

### Describe the problem

Hello,

I know this is not a BUG, But I feel to Say my issue here!

The plugin was on Spigot. Now its download is via External Site, Because of that Aternos Doesn't allow that plugin to download.

Please give a direct download option. Don't think your website is a waste because the WIKI is on your webpage so don't worry!

If you give a direct Download Option That will be really appreciated!

View the requirements here:

https://support.aternos.org/hc/en-us/articles/360052255311#h_01EPF9S3W42P6KV2P5YJ9FSF6T

When you shifted your download to an external site, Aternos Completely removed your plugin from their Plugins menu!

I can't upload your plugin because  Aternos doesn't support FTP or any kind of Upload For some reason!

Please consider Doing it please, That will be helpful : )

Thanks : )

### To Fix it?

Please give a direct download option

### Additional Information

![Screen](https://user-images.githubusercontent.com/87631878/126676782-319f7a3c-7685-4c3d-9f97-49b072b8cade.png)

**Comment by TechnicallyCoded** [comment]
Please use something else than aternos. A hosting provider that doesn't let you touch files = stupid.

**Comment by Aadi-mone** [comment]
> Please use something else than aternos. A hosting provider that doesn't let you touch files = stupid.
> The best part is that there are alternatives you can choose from that are free. Or even better, if you don't have the pocket money to pay for a server, do some quick work for someone like a relative and just pay for a server... It's soo much better rather than wasting your time on "free" options that are ridiculously bad. Plus these free options show you a bunch of ads anyway.


@TechnicallyCoded  

Thanks, for your reply,

You're Right but for some reason I use Aternos!?
I could pay, And I have a paid server, I use This plugin in that by uploading  it with the help of FTP.

I am not complaining, rather than me there are more than 100 users requesting this plugin in Aternos Board, but you know,

As Aternos TermsOfService they won't allow this plugin!

If you give the direct download option, That will be helpful & really appreciated!
We can and could pay if we want, but at the same time we must think about other users who are having problems?
And please make it to direct download.

If done please notify me!

And free services are not that bad btw, every single thing  has its own good points and bad points!

I am glad that you replied!

Thanks ~ Adarsh A  : )

**Comment by Aadi-mone** [comment]
Reply?

**Comment by TechnicallyCoded** [comment]
The decision to not provide the download through spigot itself was taken by the project's owner and I stand behind it too. You essentially asked the same question again, hence why it was ignored. I already stated the reasons behind us choosing to not change our current way of providing the plugin.

**There is no plan to change what we are currently doing to please aternos.**

If you have something against their current policies, please contact them.
