### ISSUE TITLE
Inventory lost when joining match

### ISSUE THREAD

**Issue by leviem1** [lukasvdgaag/SkyWarsReloaded#3]
In a multi-world configuration using multiverse and multiverse-inventories, players will lose the inventories of whichever world they joined from if it is not the world with the lobby spawn. No errors printed to console, just a lot of pissed off players.

**Comment by TechnicallyCoded** [comment]
We highly recommend that all players join arenas from the Skywars lobby (set using /sw setspawn). 

You can achieve this by denying permissions to players in certain worlds.

Any other method is currently unsupported and to be used at your own risk.
