### ISSUE TITLE
Scoreboard halfed in 1.8-1.12

### ISSUE THREAD

**Issue by kerostampcrab** [lukasvdgaag/SkyWarsReloaded#31]
The scoreboard is halfed because of the 1.12 and down 16 character limitation. This can be fixed, that many scoreboard plugins do, by splitting the team prefix and suffix, therefore allowing 32 characters. You can make this a togglable feature in the config.

**Comment by ninjadev64** [comment]
This needs to be asked on their [Discord](https://gcnt.net/discord)
