### ISSUE TITLE
error while saving player data

### ISSUE THREAD

**Issue by andriycraft** [lukasvdgaag/SkyWarsReloaded#40]
error while saving player data:
plugin version: 5.6.4
server version: 1.12.2

10.07 19:08:00 [Server] ERROR Cannot load plugins/Skywars/player_data/a97bb1b1-4f63-3c82-b8d7-ebe095a68d8c.yml
10.07 19:08:00 [Server] INFO org.bukkit.configuration.InvalidConfigurationException: unacceptable code point '' (0x0) special characters are not allowed
10.07 19:08:00 [Server] INFO in "'string'", position 0
10.07 19:08:00 [Server] INFO at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:55) ~[patched_1.12.2.jar:git-Paper-1618]
10.07 19:08:00 [Server] INFO at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:162) ~[patched_1.12.2.jar:git-Paper-1618]
10.07 19:08:00 [Server] INFO at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:130) ~[patched_1.12.2.jar:git-Paper-1618]
10.07 19:08:00 [Server] INFO at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:178) ~[patched_1.12.2.jar:git-Paper-1618]
10.07 19:08:00 [Server] INFO at com.walrusone.skywarsreloaded.database.DataStorage.copyDefaults(DataStorage.java:234) ~[?:?]
10.07 19:08:00 [Server] INFO at com.walrusone.skywarsreloaded.database.DataStorage.access$000(DataStorage.java:23) ~[?:?]
10.07 19:08:00 [Server] INFO at com.walrusone.skywarsreloaded.database.DataStorage$1.run(DataStorage.java:207) ~[?:?]
10.07 19:08:00 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[patched_1.12.2.jar:git-Paper-1618]
10.07 19:08:00 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.12.2.jar:git-Paper-1618]
10.07 19:08:00 [Server] INFO at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.12.2.jar:git-Paper-1618]
10.07 19:08:00 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_275]
10.07 19:08:00 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_275]
10.07 19:08:00 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
10.07 19:08:00 [Server] INFO Caused by: org.yaml.snakeyaml.reader.ReaderException: special characters are not allowed
10.07 19:08:00 [Server] INFO at org.yaml.snakeyaml.reader.StreamReader.checkPrintable(StreamReader.java:67) ~[patched_1.12.2.jar:git-Paper-1618]
10.07 19:08:00 [Server] INFO at org.yaml.snakeyaml.reader.StreamReader.<init>(StreamReader.java:45) ~[patched_1.12.2.jar:git-Paper-1618]
10.07 19:08:00 [Server] INFO at org.yaml.snakeyaml.Yaml.load(Yaml.java:437) ~[patched_1.12.2.jar:git-Paper-1618]
10.07 19:08:00 [Server] INFO at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:53) ~[patched_1.12.2.jar:git-Paper-1618]

**Comment by ninjadev64** [comment]
> `10.07 19:08:00 [Server] INFO Caused by: org.yaml.snakeyaml.reader.ReaderException: special characters are not allowed`

**Comment by andriycraft** [comment]
> > `10.07 19:08:00 [Server] INFO Caused by: org.yaml.snakeyaml.reader.ReaderException: special characters are not allowed`

what special characters? if i open the file it is empty

**Comment by ninjadev64** [comment]
oh, weird, it appears to be trying to save a null character
> 10.07 19:08:00 [Server] INFO org.bukkit.configuration.InvalidConfigurationException: unacceptable code point '' (0x0) special characters are not allowed
try backing up your SkyWars folder, deleting it, and reinstalling
