### ISSUE TITLE
java.net.UnknownHostException: my.gaagjescraft.net

### ISSUE THREAD

**Issue by andriycraft** [lukasvdgaag/SkyWarsReloaded#43]
14.10 07:45:43 [Server] WARN java.net.UnknownHostException: my.gaagjescraft.net
14.10 07:45:43 [Server] WARN at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
14.10 07:45:43 [Server] WARN at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
14.10 07:45:43 [Server] WARN at java.net.Socket.connect(Socket.java:607)
14.10 07:45:43 [Server] WARN at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:284)
14.10 07:45:43 [Server] WARN at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
14.10 07:45:43 [Server] WARN at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
14.10 07:45:43 [Server] WARN at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
14.10 07:45:43 [Server] WARN at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
14.10 07:45:43 [Server] WARN at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
14.10 07:45:43 [Server] WARN at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
14.10 07:45:43 [Server] WARN at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
14.10 07:45:43 [Server] WARN at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162)
14.10 07:45:43 [Server] WARN at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
14.10 07:45:43 [Server] WARN at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
14.10 07:45:43 [Server] WARN at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1570)
14.10 07:45:43 [Server] WARN at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
14.10 07:45:43 [Server] WARN at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
14.10 07:45:43 [Server] WARN at com.walrusone.skywarsreloaded.utilities.mygcnt.GCNTUpdater.checkForUpdate(GCNTUpdater.java:41)
14.10 07:45:43 [Server] WARN at com.walrusone.skywarsreloaded.SkyWarsReloaded.lambda$checkUpdates$0(SkyWarsReloaded.java:731)
14.10 07:45:43 [Server] WARN at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64)
14.10 07:45:43 [Server] WARN at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
14.10 07:45:43 [Server] WARN at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
14.10 07:45:43 [Server] WARN at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
14.10 07:45:43 [Server] WARN at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
14.10 07:45:43 [Server] WARN at java.lang.Thread.run(Thread.java:748)

**Comment by TechnicallyCoded** [comment]
Update the dependencies repo. We no longer own the gaagjescraft domain
