### ISSUE TITLE
IllegalStateException when getting ping in MinecraftPing.java (BungeeCord / PaperMC)

### ISSUE THREAD

**Issue by steamsyyy** [lukasvdgaag/SkyWarsReloaded#7]
JAVA_HOME: C:\Program Files\AdoptOpenJDK\jdk-11.0.9.101-hotspot\

Full error log:
https://my.gaagjescraft.net/paste?name=yEotkOVY

Lobby Server config.yml:
https://my.gaagjescraft.net/paste?name=DOevs7zk

japan:25569 config.yml:
https://my.gaagjescraft.net/paste?name=N1nbA2wz

Line(s) of code in question [(link)](https://github.com/lukasvdgaag/SkyWarsReloaded/blob/master/src/com/walrusone/skywarsreloaded/utilities/minecraftping/MinecraftPing.java): 
```java 
JsonObject obj = new JsonParser().parse(json).getAsJsonObject();
MinecraftPingReply mpr = new MinecraftPingReply(
    new MinecraftPingReply.Description(obj.getAsJsonObject("description").getAsJsonArray("extra").get(0).getAsJsonPrimitive().getAsJsonObject().get("text").getAsString()),
    new MinecraftPingReply.Players(obj.getAsJsonObject("players").get("max").getAsInt(), obj.getAsJsonObject("players").get("online").getAsInt()),
    new MinecraftPingReply.Version(obj.getAsJsonObject("version").get("name").getAsString(), obj.getAsJsonObject("version").get("protocol").getAsInt()),
    ""
);
```

Exception happens when calling `getAsJsonPrimitive()` in `new MinecraftPingReply.Description()`

**Comment by TechnicallyCoded** [comment]
Hello @steamsyyy thank you for providing a very explanation of your problem. I have worked with someone else in the past on this exact issue but they were running their game servers (not lobby) in 1.8. Would that be your case?

**Comment by steamsyyy** [comment]
Both the lobby and the server are Paper v300 (1.16.4), and are connected with BungeeCord. 

Also, this is off topic but should the plugin be automatically redirecting you to an open game if there is only 1 map? That's happened to me several times while trying to set it up, following your guide you have on your Youtube channel.

**Comment by TechnicallyCoded** [comment]
Hey @steamsyyy would you be willing to use a temporary skywars jar (in which I added more debug statements) to find what is causing this exactly? You will need to enable debug mode. (I also pinged you on discord)

**Comment by steamsyyy** [comment]
Not a problem

**Comment by TechnicallyCoded** [comment]
This issue has been solved in the latest beta
