### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by LucidAPs** [lukasvdgaag/SkyWarsReloaded#8]
Console error with latest version, Java 11
https://mcpaste.io/3b621b41f715764d

**Comment by steamsyyy** [comment]
Lines in question:

[MobSpawnEvent](https://github.com/lukasvdgaag/SkyWarsReloaded/blob/824fe6984f07cebf5bd7868cc85ba45de604c139/src/com/walrusone/skywarsreloaded/matchevents/MobSpawnEvent.java#L104)

[NMSHandler v1_16_R3](https://github.com/lukasvdgaag/SkyWarsReloaded/blob/824fe6984f07cebf5bd7868cc85ba45de604c139/src/com/walrusone/skywarsreloaded/nms/v1_16_R3/NMSHandler.java#L177)

**Comment by TechnicallyCoded** [comment]
I am decently sure that this was fixed in our upcoming version. Please download it when it becomes available and notify us if the problem was fixed

**Comment by LucidAPs** [comment]
The error above has been fixed but a new console error has emerged!
https://nekobin.com/telafotuhu

**Comment by TechnicallyCoded** [comment]
That is a separate issue, please open another github issue if you want us to take a look at it.
